意味の分かりにくい変数名を変更しました。
Yuu412/minlabo pull request #32
Opened 2020-10-03 07:19 UTC by Yuu412

・pre をprefectureに変更しました。
・facをfacultyに変更しました。

2020-10-03 22:58 UTC, TOMOFUMI-KONDO commented on database/migrations/2020_08_20_131543_create_faculty_logos_table.php
> +            $table->string('faculty_logo');
テーブル名がfaculty_logo = 学部のロゴ なので、カラム名は学部のロゴに関する何の情報なのかを表すのがいいと思います。

2020-10-03 22:59 UTC, TOMOFUMI-KONDO commented on database/migrations/2020_08_30_092439_create_prefecture_images_table.php
>              $table->timestamps();
こちらもfaculty_logosと同じくです。

2020-10-03 23:02 UTC, TOMOFUMI-KONDO commented on resources/js/components/AreaCard.vue
> +      return '/img/prefecture_image/' + this.prefectureImage
public > pre_imageのディレクトリ名も変更しないとファイルが見つからないと思います。
ブラウザでの表示の確認はしましたか？

2020-10-03 23:03 UTC, TOMOFUMI-KONDO commented on resources/js/components/EvaluationCard.vue
> +      return '/img/prefecture_image/' + this.prefectureImage
AreaCard.vueと同じくです。

2020-10-03 23:04 UTC, TOMOFUMI-KONDO commented on resources/js/components/FacultyCard.vue
>      },
AreaCard.vueと同じくです。

2020-10-03 23:04 UTC, TOMOFUMI-KONDO commented on resources/js/components/SimpleCard.vue
>      <p>{{ text }}</p>
AreaCard.vueと同じくです。

2020-10-03 23:29 UTC, TOMOFUMI-KONDO requested changes
jsファイルを更新した時は、npm run dev等でアセットのコンパイルを行ってください。
コンパイルをしたらpublicディレクトリ配下のファイルが更新されてるのが確認できると思います。

2020-10-04 00:29 UTC, Yuu412 commented on database/migrations/2020_08_20_131543_create_faculty_logos_table.php
> +            $table->string('faculty_logo');
$faculty_logo → $faculty_filenameに変更しました

2020-10-04 00:29 UTC, Yuu412 commented on database/migrations/2020_08_30_092439_create_prefecture_images_table.php
>              $table->timestamps();
$prefecture_logo → $prefecture_filenameに変更しました

2020-10-04 00:57 UTC, Yuu412 reviewed
npm run dev 気を付けます！

2020-10-04 00:57 UTC, Yuu412 commented on resources/js/components/AreaCard.vue
> +      return '/img/prefecture_image/' + this.prefectureImage
なぜかきちんと表示されています笑
というか、ディレクトリ名をprefecture_image/に変更すると、逆に上手く表示されません。

ログイン後トップページの県の画像が表示される部分（ここでは「エリアから探す」部分）に対しては、このAreaCard内のパス以外に変更後のパスを記述するところとかってありますか？？

2020-10-04 01:33 UTC, TOMOFUMI-KONDO commented on database/migrations/2020_08_20_131543_create_faculty_logos_table.php
> +            $table->string('faculty_logo');
変更確認できないのですが、pushしましたか？

2020-10-04 01:34 UTC, TOMOFUMI-KONDO commented on database/migrations/2020_08_30_092439_create_prefecture_images_table.php
>              $table->timestamps();
変更確認できないのですが、pushしましたか？

2020-10-04 01:36 UTC, TOMOFUMI-KONDO commented on resources/js/components/AreaCard.vue
> +      return '/img/prefecture_image/' + this.prefectureImage
npm run dev してから確認しましたか？

> ログイン後トップページの県の画像が表示される部分（ここでは「エリアから探す」部分）に対しては、このAreaCard内のパス以外に変更後のパスを記述するところとかってありますか？？
->ないと思います。

2020-10-04 01:39 UTC, Yuu412 commented on resources/js/components/AreaCard.vue
> +      return '/img/prefecture_image/' + this.prefectureImage
はい、npm run dev後です。

2020-10-04 01:40 UTC, Yuu412 commented on database/migrations/2020_08_30_092439_create_prefecture_images_table.php
>              $table->timestamps();
申し訳ないです！
今しました。

2020-10-04 01:40 UTC, Yuu412 commented on database/migrations/2020_08_20_131543_create_faculty_logos_table.php
> +            $table->string('faculty_logo');
申し訳ないです！
今しました。

2020-10-04 04:27 UTC, TOMOFUMI-KONDO commented on resources/js/components/AreaCard.vue
> +      return '/img/prefecture_image/' + this.prefectureImage
Slackで話しましょう。

2020-10-04 15:42 UTC, Yuu412 commented
画像がきちんと表示されない不具合を解消しました。

2020-10-04 23:37 UTC, TOMOFUMI-KONDO approved these changes

2020-10-04 23:37 UTC, merged